name: assemble
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.0
  args: ^2.3.0
  http: ^1.2.2
  graphviz2: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
