name: assemble
description: Assemble is a command-line tool designed for Flutter developers to analyze and manage project dependencies efficiently.
version: 1.0.0
homepage: https://github.com/Nolle10/assemble
repository: https://github.com/Nolle10/assemble

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.0
  args: ^2.3.0
  http: ^1.2.2
  graphviz2: ^1.0.0
  html: ^0.15.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
